slam_toolbox:
  ros__parameters:
    mode: mapping
    map_file_name: ""
    base_frame: base_link
    odom_frame: odom
    map_frame: map
    scan_topic: /scan
    use_map_topic: true
    use_sim_time: false
    provide_odom_frame: false
    publish_tf: true
    map_update_interval: 1.0
    map_publish_period: 1.0
    use_scan_matching: true
    min_laser_range: 0.15
    max_laser_range: 5.0
    use_scan_barycenter: false
    minimum_time_interval: 0.0
    transform_publish_period: 0.05
    transform_timeout: 0.5
    map_save_interval: 0.0
    resolution: 0.05
    chunk_processing_retries: 10
    use_pose_correction: false
    scan_queue_size: 10
    covariance_scale: 0.001
    predict_duration: 0.05
    throttle_scans: 1
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.1745
    loop_search_maximum_distance: 3.0
    loop_search_maximum_angle: 0.785
    loop_match_search_radius: 0.5
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_chain_gap: 5
    loop_match_maximum_variance: 2.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
